### ISSUE TITLE
Adding my App

### ISSUE THREAD

**Issue by rahuljoban** [atlassian/nucleus#24]
Once I have launched nucleus, how to I add my existing app to the nucleus server. It is on my local machine, GitHub, and bitbucket.

**Comment by MarshallOfSound** [comment]
Hey @rahuljoban 

Simply click the `+` button in the left sidebar to add an app to Nucleus.  Once the app has been created you can follow the [Uploading](https://github.com/atlassian/nucleus/blob/master/docs/Uploading.md) instructions on how to upload releases 👍
