### ISSUE TITLE
[QUESTION] How to remove previous release files?

### ISSUE THREAD

**Issue by Stoyvo** [atlassian/nucleus#27]
We had a bad release and would like to make sure this file is not accessible.

How do we remove the previous releases, safely? It's already marked as Dead.

**Comment by Stoyvo** [comment]
Hey @MarshallOfSound 

I was thinking maybe something along the lines of:

If release is marked dead, provide option to archive files elsewhere (non-public location) or remove files in that release. 

I would hope many app developers have their own archive of their releases, but Nucleus could partially provide that (with moving dead files to archive). I personally do not need the previous releases made available based on my CI cycle.

**Comment by MarshallOfSound** [comment]
> If release is marked dead, provide option to archive files elsewhere (non-public location) or remove files in that release.

This will make the update server non-deterministic.  I.e. Files that once existed will not exist any more and this is a bad idea (especially for something as critical as an update server)

**Comment by MarshallOfSound** [comment]
As part of the work in #35 my suggestion above will be implemented.

> maybe we should make it so if the latest version is marked as dead all the metadata files are updated to not include those versions
