### ISSUE TITLE
[QUESTION] How do you generate gpg key?

### ISSUE THREAD

**Issue by DinkoMiletic** [atlassian/nucleus#30]
I am pretty new to this one and google does not offer me straight answer. 

How do you generate both public/private key without password? 

Thank you.

**Comment by MarshallOfSound** [comment]
GitHub actually has some good docs on generating GPG keys, just leave the password field blank when generating to generate without a password.

https://help.github.com/articles/generating-a-new-gpg-key/

**Comment by leofidus** [comment]
I think it would be very beneficial to add both this link and a guide on the correct format of the keys to the config-template.js

When I first tried this I found the same guide, but then got the format of the config variable wrong (the order of public and private key is assumed but not documented)

**Comment by MarshallOfSound** [comment]
> (the order of public and private key is assumed but not documented)

Oh yeah, I can see how that would be a problem, I can add that order validation to the new GPG checking logic I added 👍
