### ISSUE TITLE
Static files url is NOT working in windows

### ISSUE THREAD

**Issue by khrono-angel** [atlassian/nucleus#31]
Hi Comunnity,

I noticed that static server is not running in windows. The website server and endpoints are worning fine.

After a couple of hours trying to run the server in windows, I found that the script that runs the the command is... `start-static`... which runs `mkdir -p .files && serve .files --port 9999`...  well, the command `mkdir` in windows does not accept the `-p` argument... 

I will work on a fix for this and send a CR to contribute..

Regards

**Comment by MarshallOfSound** [comment]
@khrono-angel Sounds good 👍
