### ISSUE TITLE
[QUESTION] autoUpdate on Linux

### ISSUE THREAD

**Issue by DinkoMiletic** [atlassian/nucleus#33]
[auto-updater](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) clearly states that there is no built-in support for auto-updater on Linux. 

But nucleus API has option to check for updates and fetch package not matter what is app environment?

Did you try to implement auto update on Linux? 
If not what would be correct path in implementing one?

**Comment by MarshallOfSound** [comment]
Nucleus doesn't exactly implement "auto updating" on linux, what we do is create both `apt` and `yum` repos that your users can install your packages from and get updates just like they would any other installed linux package.

E.g. On debian

```bash
# Follow repo set up commands from nucleus
sudo apt install my-package
sudo apt upgrade my-package
```
