### ISSUE TITLE
Error 409 Release already in progress

### ISSUE THREAD

**Issue by bastientanesie** [atlassian/nucleus#39]
Hi there!

Up until yesterday I was using [`nucleus-server`](https://www.npmjs.com/package/nucleus-server) v0.7.5 in a dev environment, hosting both the release server and static files under the same host (release on port 8080, static files with [`serve`](https://www.npmjs.com/package/serve) on port 8181) and everything was working fine.

I decided to deploy Nucleus on a soon-to-be production server, nginx in front of nucleus do manage to seperate host (release.myapp.com for Nucleus, update.myapp.com for static files) and enabling Let's Encrypt SSL.

I put my config files [in this gist](https://gist.github.com/bastientanesie/54c15b4a493377ab6077e0f75f879906) :

- [`/srv/nucleus/config.js`](https://gist.github.com/bastientanesie/54c15b4a493377ab6077e0f75f879906#file-srv_nucleus_config-js), my Nucleus config file (I usually use environment variables, but replaced them with pseudo-values)
- [`/etc/nginx/conf.d/proxy.conf`](https://gist.github.com/bastientanesie/54c15b4a493377ab6077e0f75f879906#file-nginx_conf-d_proxy-conf)
- [`/etc/nginx/sites-available/release.myapp.com.conf`](https://gist.github.com/bastientanesie/54c15b4a493377ab6077e0f75f879906#file-etc_nginx_sites-available_release-myapp-com-conf)
- [`/etc/nginx/sites-available/update.myapp.com.conf`](https://gist.github.com/bastientanesie/54c15b4a493377ab6077e0f75f879906#file-etc_nginx_sites-available_update-myapp-com-conf)

Everyting seemed to be working well: I was able to upload a first version of my app with [`electron-forge`](https://www.npmjs.com/package/electron-forge) v5.2.2 on nucleus, and release it.  
The Electron's autoUpdater was correctly configured in the app, and it was polling info like it should (telling everything was up-to-date).

The problem came when I wanted to release a new version of the app. The upload worked fine, I found the draft version inside nucleus but was unable to release it: all I got is 409 errors "Release already in progress".  
I couldn't find any clues about [that error](https://github.com/atlassian/nucleus/blob/v0.7.5/src/rest/app.ts#L281)... I'm stuck! 😞

All was working well up until I added nginx. Could that be the source?

**Comment by MarshallOfSound** [comment]
@bastientanesie That error was designed to prevent race conditions when performing actions in the file store.  There was however a bug in `0.7.4` --> `0.8.0` that prevents locks being released.

If you update to `0.8.1` locks will be released properly.  Sorry 'bout that 😄 

https://github.com/atlassian/nucleus/blob/master/CHANGELOG.md

**Comment by MarshallOfSound** [comment]
Also just wanna say thanks for the super detailed issue report, it makes my life so much easier when all the information is provided up front 😸

**Comment by MarshallOfSound** [comment]
@bastientanesie Oh hm, we switched to deploying internally using docker I guess I forgot to publish `0.8.x` with npm 😆 

Let me see if I can deploy this from home, otherwise I'll do it tomorrow morning

**Comment by bastientanesie** [comment]
NP @MarshallOfSound, that happens ^^... I'll keep checking for the new version and I'll let you know if this fixes my problem 👌

**Comment by MarshallOfSound** [comment]
@bastientanesie `0.8.1` is now live on npm 🤔 😄

**Comment by bastientanesie** [comment]
Thanks @MarshallOfSound! I'll give it a try as soon as we get back our office internet connection 😅

**Comment by bastientanesie** [comment]
@MarshallOfSound it works! 🎉  
I called `/rest/admin/release-locks` and was able to release the drafted version. Thank you for you support and quick answers! Cheers 😄
