### ISSUE TITLE
Sequelize deprecated String based operators

### ISSUE THREAD

**Issue by Wolvan** [atlassian/nucleus#42]
Trying to download and run the docker image leads to the following error message

```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:236:13
```

The container does not seem to properly start up

**Comment by MarshallOfSound** [comment]
That warning is expected and it's coming from one of our dependencies.

The docker image that we publish won't run by itself, you need to extend it with you config file as described in the README for it to work.

**Comment by Wolvan** [comment]
I did put in a previously working config.js. This message is all all that appears after the index.js gets loaded.

**Comment by MarshallOfSound** [comment]
@Wolvan In your docker file can you set the `DEBUG` environment variables to `nucleus*`.  It should give you more logs if you think it's not starting up correctly

**Comment by Wolvan** [comment]
Alright, I'll try and respond tomorrow

**Comment by Wolvan** [comment]
Turns out the server did start, but with the default config.template.js that you supply in this repo the server starts on port 3030, not 8080 as specified in the Readme. Sorry again about this false issue report, maybe change the misleading port in the Readme.md to avoid further wrong port problems

**Comment by Wolvan** [comment]
Should there be a debug message when the server on port 9999 goes up? Because I am not getting one and connection to that port is always denied

**Comment by Wolvan** [comment]
Another stupid question, but I tried writing my own uploader and when I hit the `${config.host}/rest/app/${config.appId}/channel/${config.channelId}/upload` endpoint, Nucleus returns a 404: `{"error":"Unknown Path"}`. What causes this?

**Comment by MarshallOfSound** [comment]
@Wolvan That will be because you aren't providing the token correctly.  We 404 on the upload route if a bad token is provided to prevent people brute force guessing channel ID's

**Comment by Wolvan** [comment]
Thanks a lot for your help, Marshall, I appreciate it a lot. Server seems stable and so does my self made mini uploader. And sorry for bugging you with my dumb questions

**Comment by factorone** [comment]
> @Wolvan The static server on port `9999` is only launched in development when running from source.
> 
> https://github.com/atlassian/nucleus/blob/master/package.json#L24
> 
> It is assumed if you're using the Docker image that you're running for production and are using your own file store

I've literally poured through everything I can find on this system, trying to figure out why I can't get anything to respond on port 9999, and was on the precipice of opening a new issue for that when I stumbled upon this comment. 

Based on what you're saying, if you're just trying to utilize a local file system instead of abstracting file storage off to another platform (e.g. S3), what's your suggestion for configuring things to allow the file store option to work if you're using the Docker setup?

**Comment by Wolvan** [comment]
I actually just added an apache server listening to port 9999 and serving the files that are stored locally by nucleus when you push files to it. Put an nginx reverse proxy before it to give it SSL and that works out pretty damn well for me

**Comment by factorone** [comment]
Did you run that in another Docker container and just network the two together, or did you run that as a standalone setup? I'm still relatively wet-behind-the-ears when it comes to running DevOps stuff, especially with AWS, and Docker isn't necessarily making things any less complex or easier to handle.

**Comment by Wolvan** [comment]
Yeah I think it's a 2nd docker container with an apache image. Both use a shared volume. When you upload nucleus saves it in the volume and the volume is hooked as apache's htdocs iirc. You can add an nginx reverse proxy docker image in front of both to give them ssl and have that expose the actual web ports

**Comment by factorone** [comment]
I've been experimenting with this all morning, and I'm not quite 100% there. Could you possibly send me an email with the configs for this setup (mainly just need port/path/volume details)? I've got things configured where they _should_ be working, but it's not quite there yet.
