### ISSUE TITLE
TypeScript : error TS18003: No inputs were found in config file

### ISSUE THREAD

**Issue by mgara** [atlassian/nucleus#45]
Thanks for this awesome project : 

I run in many issues while trying to build the server for prod use , especially when I tried to install the server on a vanilla CentOS.

After digging I ended up with this issue when running : yarn build-server (tsc)

error TS18003: No inputs were found in config file

**Comment by mgara** [comment]
CentOS Linux release 7.4.1708 (Core) 
Node  : v8.11.3
npm : 5.6.0


Also required: 
npm install -g nucleus-server webpack webpack-cli
yum install bzip2

**Comment by MarshallOfSound** [comment]
The best way to use nucleus is through our docker image, everything will work out of the box and all the required dependencies will already be installed,  We unfortunately don't have the resources to help people with set up issues in their own custom environment, this is why we build the docker image 👍
