### ISSUE TITLE
NPM version is behind GitHub Release version

### ISSUE THREAD

**Issue by Stoyvo** [atlassian/nucleus#50]
https://www.npmjs.com/package/nucleus-server

Latest release is 0.8.1, GitHub is 0.8.3

**Comment by MarshallOfSound** [comment]
@Stoyvo This is expected as of `1.0.0` we dropped `npm` as a release target.  The two supported techniques now are "manual" and "docker".

See the README --> https://github.com/atlassian/nucleus#setup
