### ISSUE TITLE
Webpack does NOT get built

### ISSUE THREAD

**Issue by ppuvanasingam** [atlassian/nucleus#55]
I am new to this project and I recently got this server setup. However, I couldn't get the web UI to work at first. `public_out` folder was not being generated at all.

I ran into the issue of webpack not being built automatically when I run `yarn dev`. I had to manually run the script `webpack --config webpack.config.js` via `npm` for it to generate the public_out folder.

I was wondering whether is this a known issue or something I did wrong, but wasn't able to find a similar issue online, so I thought of posing this hoping it could be useful to someone.

**Comment by MarshallOfSound** [comment]
`yarn dev` doesn't generate any webpack output, it runs the webpack dev server.

`yarn build-fe-prod` will run webpack and generate prod bundles.

**Comment by ppuvanasingam** [comment]
Thank you @MarshallOfSound, which is what I end up doing; but the documentation doesn't mention anything about it, thought it would be useful to someone.

**Comment by MarshallOfSound** [comment]
@ppuvanasingam We don't recommend that you build Nucleus yourself (which is why we haven't documented any of those commands).  We provide a ready-to-run Docker image that has everything pre-built and ready for prod use.

https://github.com/atlassian/nucleus#docker
