### ISSUE TITLE
Unable to Setup following Docker instructions

### ISSUE THREAD

**Issue by ericwu-eWorldES** [atlassian/nucleus#58]
@MarshallOfSound 

Created an empty directory on my system called nucleus and created a Dockerfile with only these lines

```
FROM atlassian/nucleus

COPY config.js /opt/service/config.js
```

After that I ran the command

`docker build nucleus .`

But I'm given this error message at the end, which causes nucleus to not work when I run the docker image.
`Step 2/2 : COPY config.js /opt/service/config.js
COPY failed: stat /var/lib/docker/tmp/docker-builder498034705/config.js: no such file or directory`

Please advise

**Comment by ericwu-eWorldES** [comment]
Following the manual instructions doesn't work either. Here is an output file if you could help with this. Thank you

[output.log](https://github.com/atlassian/nucleus/files/2485515/output.log)

**Comment by MarshallOfSound** [comment]
@ericwu-eWorldES The docker error is because you need to make a `config.js` file in your current directory for the dockerfile to copy.

The manual error you are getting is because you don't have the cpp build tools installed on your machine

**Comment by ericwu-eWorldES** [comment]
@MarshallOfSound would I use your config.template.js as the config.js to make it work?

**Comment by ericwu-eWorldES** [comment]
@MarshallOfSound I confirmed that I had Python 2.7.15 and Visual Build Tools 2017 installed when performing the manual instructions. However, the project still gives me errors and won't build. Please advise
