### ISSUE TITLE
GPG Signing issue

### ISSUE THREAD

**Issue by JasSra** [atlassian/nucleus#59]
I downloaded the most stable release of nucleus and set up yarn , copied config.template.js to config.js and then yarn dev as directed. However it gives me an error of GPG key, as the config says it needs it to sign and gives me a proxy error too. I am just setting up my dev machine, do i really need to have a gpg key,if yes then how you do it, if not then how can i bypass it so as just to run my development machine, so that i can test my electron app. 

The proxy error is :[HPM] Error occurred while trying to proxy request /rest/config from 127.0.0.1:8888 to http://localhost:3030 (ECONNREFUSED)

I am running macos mohave , node 10.xx

Btw: i am new to the gpg system. I have generated one and its in my profile folder, but what to do with it ?

Thanks,
Jas

**Comment by MarshallOfSound** [comment]
GPG keys are required, the proxy issue is because the backend didn't start because you didn't configure a GPG key.

Details for GPG set up if you've never done GPG stuff before can be found here https://github.com/atlassian/nucleus/issues/37#issuecomment-391399362

**Comment by JasSra** [comment]
Just generated a gpg key as directed, and did yarn dev, now i get "cannot get/ "  ->  app crashed : Could not locate config.js file, please ensure it exists

Its there since i copied from config.template.js to config.js and updated gpg in the same directory .

Thanks a ton for gpg, 👍  btw: the --export-private-key is now called --export-secret-keys !
Thanks

**Comment by leofidus** [comment]
"Could not locate config.js file" is a misleading error message, it also happens if config.js contains a syntax error.
