### ISSUE TITLE
config.js for Docker

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [atlassian/nucleus#76]
It seems that https://github.com/atlassian/nucleus/blob/master/config.template.js lacks some required information.
I can't make the server fully functional with the documentation provided.
It seems that I have to run the separate container to serve static content. With the empty entrypoint and `npm run start:static` BUT there is no `make-dir` & `serve` commands in path. So I have to add  `RUN yarn global add serve` to the Dockerfile and run it with `serve .files -l 9999` and still have issues.
That's really weird.

**Comment by MarshallOfSound** [comment]
@Ilya-Kuchaev `serve` is a [dependency](https://github.com/atlassian/nucleus/blob/master/package.json#L130) in our package.json.  If it's not on your path you haven't installed the modules correctly 👍 

Also the `config.template.js` is mostly aimed at the development scenario, in production you should **not** be using the `serve` / local file strategy.  You should be using S3 or a different storage provider as nucleus itself should not be exposed to the internet.
