### ISSUE TITLE
Multiple platforms under same version

### ISSUE THREAD

**Issue by Wolvan** [atlassian/nucleus#77]
Today was the first time I tried to create targets for both windows and mac (before it was always mac only). Trying to upload the files to the upload server made me realize, that it drafts multiple releases, one per platform.

Furthermore, when I release both of them, the one I released later overrides the one I first clicked on release, instead of them merging into a single release.

How are we supposed to handle multi-platform releases exactly?

**Comment by MarshallOfSound** [comment]
> the one I released later overrides the one I first clicked on release

They don't override each other, release one and wait for it to complete, then release the second one, they will be merged 👍

**Comment by Wolvan** [comment]
Oh, looks like it was a visual glitch then. Sorry for the wrong issue, because when I checked the thing the first time it was missing the files for macos after I approved the windows files
