### ISSUE TITLE
how to use gpgsigningkey

### ISSUE THREAD

**Issue by allenlongbaobao** [atlassian/nucleus#86]
i'm  using the dockerfile solution. In config.js, gpgsigningkey must be provided. then I use GPG keychain generate the no password gpg, but, what is the very gpgsigningkey, anyone help?

**Comment by jezzdk** [comment]
Check this out: https://github.com/atlassian/nucleus/issues/37#issuecomment-391399362

**Comment by b-zurg** [comment]
This should be part of the docs I think. It's going to cause many who begin using it some confusion
