### ISSUE TITLE
latest release for darwin arch missing

### ISSUE THREAD

**Issue by masterkain** [atlassian/nucleus#88]
hello,
thanks for nucleus, I'm still learning about it.

during my test drive when I promote and rollout releases from draft to published I find there are linux and windows ones but the build for darwin is missing.

the darwin release is produced by `@electron-forge/maker-zip` on travis CI, the package exists and I can download it via the modal window, however the url is /myapp/5bc3702a82f36211a0bd4d5e431f74ca/_index/1.3.5/darwin/x64/myapp-darwin-x64-1.3.5.zip

is there anything I can check why this happens? should I provide a .dmg maybe?

the debug shows it is rolling out also `darwin/x64/100/RELEASES.json`, however it does not appear in the latest folder with everything else.

**Comment by masterkain** [comment]
made dmg, all good

**Comment by RouR** [comment]
RELEASES.json is empty
also for dmg

it`s a problem :(
